# do not install anything extra onto the image
language: generic

# use a Mac OSX image
os: osx

# only run builds on pushes to the master branch
branches:
  only:
  - build

# send email notifications when the build changes from succeeding to broken
notifications:
  email:
    on_success: never
#    on_failure: change

# decrypt the encrypted SSH key file so it can be used for scp auth in post_build.sh
#before_install:
#- openssl aes-256-cbc -k "$KEYFILE_PASS" -in "${UPLOAD_KEYPATH}.enc" -out "${UPLOAD_KEYPATH}" -d

# run the script to download and install Unity editor
install:
- sudo -E sh ./Scripts/install.sh

# run the script for unit tests and builds
script:
- sudo -E sh ./Scripts/build.sh

# run the script to upload the builds as tarballs
#after_success:
#- sudo -E sh ./Scripts/post_build.sh

# environment variables used in bash scripts
env:
  global:
  - UNITY_PROJECT_NAME="TravisUnityProject"
  - DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV"
  - secure: "FL6gzxPnmfvenZ99sE4Fk+VVT+xVBo9FIqsPJTR4IJRAVUuSmdLBkmj5tsaQoTIT+Ry5BF9VGkMNE64BYnpRa/FV0vHskJlY4EmJ3gYOIgBcgulwVaZuvGZr9VHCvVuCqcXnMQoyOkJqC3OtmRQ/XAbcjcBJ8C43CPKnG4cOvk4VwbnjoRuB2oNGlv1o8sDHKZiQaQJl+9ShafjhrW3WrlaHK92WDz7KBacPOZqd0L3wq6kdsy0BWFXyihRhs5Ddcuw9eVerzQ63vWU0u7vKbKrURtwO7SuY4/fJWR1LvGpPqRNCwg+iNVGsUTjWyUxkPVyRRr71UuOmbx9z8MQJFNNnOU12836pKczVSDs5av0Khkg+BFF7RCQDjNNwErgjbONehlD2T+lwBKWXnNGAlttEpeiFHEqMVoj0d13gnrjLclRhmHwqXl+hB6hc7J7gUv9dz/2urKJ24n17PMeW+Hp7KlVXEn9bHFFoWvsUDgVaew1EbL485jRHqFD5Xzg9KISrNupg5PD23TZskeceouZheIMvgYHonmNo0M5TSsCR/VD1eGURusX3hAEj+0OuSQBAcmyej5D/gS2J1z2q+yt0zW39ob2bHOVKAhR4XYqq6zKcCDxrYfC4Ic+xN4FNIBVyLpKKyvWsFqTkQ21S35bcpBXG51mDkJuZrZH+ATc="
  - secure: "GsXSe8tgNNL7dPWJsiYB4oaXrisHDlvBx8pOyPBEhYs8y796P/7Cb9d7hHt9HI5tS1LLlM3fQ/ogBfbtb4usiEnGxRazKcB98vWeuYyEAAqndk4Zlk32z1LEJPA4dDDy33R65VqhtI5zledKIPGCp5UK3NWSfge0h5rMlBsrM9XzT8oXEPLM15RF5A2ZlzG6HesWJMwi0aAz03Ehb0fpbty/5daQJ77eu4X/LvYL8vS/3OrG32D4F32qZ92RL32E9RM/iSLrRFhth+b3BenrI6rnUz9KefLqQ9zd4uCdfwVjsIcq/KKSbvlFOYx1ZmCyqQgBQSTLS/rAka1H2r0UDc9NirCoGRqxEriHkNbH9crq7z9IEQrpR7OzJag/++8y1gdJVV2HRSYG9kKoggF/MZTyug4ZVLI247swzOT7rvNwq2jKr1RwrF7AJftKwVX9ZreL6tKccPAhHawa3cDE4SkMlMHcJkp/zVmjtELoc42ZQ43Rjf9Fzty0S9nrPnaOaBYc71y+SRUoT+HtZyxlYmEOr7ktNCmsjjbc5Ax82rNQyEMRmYrnceaZt2wTvAF9XO6SN8uE8X0jkp8on8LUMvOH18odTqtaH8yuOJYK3s5FJ6nAExdSl84WknXSuv7ys7/O2SHEgB9haDkwxbJa44eZZpvM1JfKsNCpJ+elZKA="
  - secure: "gv6thR3Q2abol6Wc4SJTYUJO5HQEJZKyPv33tyiy5KOLCm4e11oh19uC5qDcRotXafYneCr6pomyUEvwpqw+B1KpiZk5/KxfnTCWO/vfLHUw9xoBevdqLBOEqpT5dr1B8Y65x7cJI23chpETpKcJcWTM1ZTBa5OWN+Dm/ZZNAVQVT3GvDD0/biMuDu+6rafIzhfl+G+w9AgwHzjH49pwFT52nyBcJcpEVO6fqkFUgTjm2TqshShBfFKvQG8LeZ8/xxYF9kcKV680v/7wj0783qBKQKR5lLTioFVZU0vazhMBXW/0nM6rhM6wJCUyb/iyTVauyyWhpJfTmccaOzBBAsN0xjCZEtuzlXhBAJtt+RjmrRL+FKC0jWZ4fMtk5FqUzm5frEx2XqumtNI+hiZ5crq/9Et3cqWVnlwyGzmxWlkeHNczUEjtje4Zxf81ch6TgpOxqc52t5LUBo6xqzoZ1k4TTsIaN7Ei7ahabXW0816zwfjKJsoRukYbGXBLbctGmnej4Z76rtbNh5zDyPTOvnMyGE0cWb9OP+FPh3CC0mu5uBEPPym7UWxpOdIXM5efWt+mRX72b6o+RwK6cazYMVNXlymlJmRcAMOKxM15q3HVrUyL/VPUZw44PjQOO21IEy+Nr0LkSWtM2Jjyj+QI/O9mV4qZDHk86ks/nbHtYJc="
