# do not install anything extra onto the image
language: generic

os: osx

branches:
  only:
  - build

notifications:
  email:
    on_success: never
#    on_failure: change

cache:
  directories:
  - $UNITY_DOWNLOAD_CACHE

# decrypt the encrypted SSH key file so it can be used for scp auth in post_build.sh
before_install:
- sudo -E sh ./Scripts/before_install.sh
#- openssl aes-256-cbc -k "$KEYFILE_PASS" -in "${UPLOAD_KEYPATH}.enc" -out "${UPLOAD_KEYPATH}" -d

install:
- sudo -E sh ./Scripts/install.sh

script:
- sudo -E sh ./Scripts/build.sh

#after_success:
#- sudo -E sh ./Scripts/post_build.sh

env:
  global:
  - UNITY_NOPROXY="localhost,127.0.0.1"
  - UNITY_DOWNLOAD_CACHE="${TRAVIS_BUILD_DIR}/unity_download_cache"
  - UNITY_PROJECT_NAME="TravisUnityProject"
  - DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV"
  - secure: "FL6gzxPnmfvenZ99sE4Fk+VVT+xVBo9FIqsPJTR4IJRAVUuSmdLBkmj5tsaQoTIT+Ry5BF9VGkMNE64BYnpRa/FV0vHskJlY4EmJ3gYOIgBcgulwVaZuvGZr9VHCvVuCqcXnMQoyOkJqC3OtmRQ/XAbcjcBJ8C43CPKnG4cOvk4VwbnjoRuB2oNGlv1o8sDHKZiQaQJl+9ShafjhrW3WrlaHK92WDz7KBacPOZqd0L3wq6kdsy0BWFXyihRhs5Ddcuw9eVerzQ63vWU0u7vKbKrURtwO7SuY4/fJWR1LvGpPqRNCwg+iNVGsUTjWyUxkPVyRRr71UuOmbx9z8MQJFNNnOU12836pKczVSDs5av0Khkg+BFF7RCQDjNNwErgjbONehlD2T+lwBKWXnNGAlttEpeiFHEqMVoj0d13gnrjLclRhmHwqXl+hB6hc7J7gUv9dz/2urKJ24n17PMeW+Hp7KlVXEn9bHFFoWvsUDgVaew1EbL485jRHqFD5Xzg9KISrNupg5PD23TZskeceouZheIMvgYHonmNo0M5TSsCR/VD1eGURusX3hAEj+0OuSQBAcmyej5D/gS2J1z2q+yt0zW39ob2bHOVKAhR4XYqq6zKcCDxrYfC4Ic+xN4FNIBVyLpKKyvWsFqTkQ21S35bcpBXG51mDkJuZrZH+ATc="
  - secure: "GsXSe8tgNNL7dPWJsiYB4oaXrisHDlvBx8pOyPBEhYs8y796P/7Cb9d7hHt9HI5tS1LLlM3fQ/ogBfbtb4usiEnGxRazKcB98vWeuYyEAAqndk4Zlk32z1LEJPA4dDDy33R65VqhtI5zledKIPGCp5UK3NWSfge0h5rMlBsrM9XzT8oXEPLM15RF5A2ZlzG6HesWJMwi0aAz03Ehb0fpbty/5daQJ77eu4X/LvYL8vS/3OrG32D4F32qZ92RL32E9RM/iSLrRFhth+b3BenrI6rnUz9KefLqQ9zd4uCdfwVjsIcq/KKSbvlFOYx1ZmCyqQgBQSTLS/rAka1H2r0UDc9NirCoGRqxEriHkNbH9crq7z9IEQrpR7OzJag/++8y1gdJVV2HRSYG9kKoggF/MZTyug4ZVLI247swzOT7rvNwq2jKr1RwrF7AJftKwVX9ZreL6tKccPAhHawa3cDE4SkMlMHcJkp/zVmjtELoc42ZQ43Rjf9Fzty0S9nrPnaOaBYc71y+SRUoT+HtZyxlYmEOr7ktNCmsjjbc5Ax82rNQyEMRmYrnceaZt2wTvAF9XO6SN8uE8X0jkp8on8LUMvOH18odTqtaH8yuOJYK3s5FJ6nAExdSl84WknXSuv7ys7/O2SHEgB9haDkwxbJa44eZZpvM1JfKsNCpJ+elZKA="
  - secure: "gv6thR3Q2abol6Wc4SJTYUJO5HQEJZKyPv33tyiy5KOLCm4e11oh19uC5qDcRotXafYneCr6pomyUEvwpqw+B1KpiZk5/KxfnTCWO/vfLHUw9xoBevdqLBOEqpT5dr1B8Y65x7cJI23chpETpKcJcWTM1ZTBa5OWN+Dm/ZZNAVQVT3GvDD0/biMuDu+6rafIzhfl+G+w9AgwHzjH49pwFT52nyBcJcpEVO6fqkFUgTjm2TqshShBfFKvQG8LeZ8/xxYF9kcKV680v/7wj0783qBKQKR5lLTioFVZU0vazhMBXW/0nM6rhM6wJCUyb/iyTVauyyWhpJfTmccaOzBBAsN0xjCZEtuzlXhBAJtt+RjmrRL+FKC0jWZ4fMtk5FqUzm5frEx2XqumtNI+hiZ5crq/9Et3cqWVnlwyGzmxWlkeHNczUEjtje4Zxf81ch6TgpOxqc52t5LUBo6xqzoZ1k4TTsIaN7Ei7ahabXW0816zwfjKJsoRukYbGXBLbctGmnej4Z76rtbNh5zDyPTOvnMyGE0cWb9OP+FPh3CC0mu5uBEPPym7UWxpOdIXM5efWt+mRX72b6o+RwK6cazYMVNXlymlJmRcAMOKxM15q3HVrUyL/VPUZw44PjQOO21IEy+Nr0LkSWtM2Jjyj+QI/O9mV4qZDHk86ks/nbHtYJc="
  - secure: "To1TdWURVOUIDur3sKVyjLefGWFnVhLmhRCZuB0QMiyMuWy89v9xj5NjIUTNmhp9YKsEYPjMUip6nan512VTqpqUr7m9OjXcIyMqngd7hHegK+/B2vh/4TBZNyUGwoNMHp4NhoN11rznswxa3jZjfbsWVM7lmdaJTuFkHCMYZTYxJ9ALpXlwYJE0btlbMAgUh59WFv+kpBvVdsJqhjtL+xT0HOqr8q7kfZpWC1iGAIEcsrvxaJpnxkJ295J5tekfmgvY2pZEt0G8S2HoTL79wqSQSNiUznXHgw7d+J2HJ51s5LnxapkEho+HH8B0bbI27u5u/5f7kX9rv7G7LuP0ihnEFCL0dCodp00F9BuEgqJdwa5HRl0RQVt0b/3cPPVLCDBnkX+8464GBX6tVV8HKEifkv7+eMpSdRKNzUj5Yim1azylAmI2xz7e66+63huQpPaWc+c9pb3yWVVDN1hnG1HodAf9L0t12r6FxcJOf7PqopwJQMwCJSgPAQ5IzsmgtH1CUMosf/Sod4k+veqfVTTYPiilf1yyFCU8MErmXx7/2ZdKezWznlsg/bHMDOfXe0xi0af3eZR/g5SCL0gRUSQQtmdkSk0LjXnyZFqAk1odk3N3Z2CQa7ve6GoR9S3uvp7Hh9LR8AnatRV1SbLKMZlCi7NkSQLeJ2oQ74mN6Kc="
  - secure: "G1tyzhtmIagcjzpoSzMBXw9nR0lmyxDoPBwLkHl18cNzV8silpGCMGNJ7Q4c0ODUHBlYB3wR8CaGqsqSjJ/xtQoC4XX6mChLpmdV14o1PSYe+QUZQhsUwuAyWKlFUHywqY3G0bdmMrL0/68/DjB/yOUz9IOsu6ObdMnleTbO4UhTudLZSlWFc7XeWQmn+wEEPhKhEHOomDjwpf1NEuY7phX8HZMu/ji1wGuXUsv0WuTyFKtHe7UbJlX4Gnu0hWVtmUHW432r8H84bHFrL9yovihwp/5VptVU/XZwf1PC1RwOoHpjYNWwGlDdvrYbEMki7v3PqqObadhSXtMlPqpnpnAt2f9bQuD4fAWZEj1HTfNjkRk+A1Eaci1NPRg9StOiNFmiK6cqoiEAEPB30kyFrah/Lz4gs9rNQvbvZ3wYF3sAbj3rL9TcTNgr8WCEvfJuXhTf9dT8XzCnBadbsoPMwqMxa9S4UK45cyTIfTPSza0xfYsZJQ8IBxvUszjyxprVas+QJDjsn1xkhDmUEg0/FqhNEmJ5iAOP46Wv26RsvBi/SndSfyoE1GJJSz6Rcb1O0TI5WPHOgV698pWKXwT4wnLhmSvhjrOPtDosGylalLgwDHxITn/Oxiz+owVolIigbTn8EPLsvJkPSuerYpDtlY2UbE1GwTnYsZUpZU7dyIs="
  - secure: "qFZ14DxJEhPGyEqsXBYo4ZN/MsH9ifgi6U99z+i8MzxcKqjwa3DoB44lSpGYsKBDmE03/JCxLXIoMF4qJejqkSpzYyRVAPl9Gl6GXn4U+G8eTAXetIDb/tA3c+1stPFvHFn+sFhXSdpGWgdCOiIUFKaClsVL9fmUDMnNIXwKp6VRp9l+Ey+ITawAkYsrBcehebYoMrmYf8W3BC5AB5Qs9cnKBlPA1euJgopUc8urpYFsoIp+LoKGRga3K7cq5m96co5WXaxFgXUgSI4G9yhDLeBtVyqjjDeI7TW7wZoMGG20DWqFhaKT6CEm+LG3gdtr2/egYmDr6B5Zxx6q1ndIIY8wg/KmRsTZ/zzjHj6ODjkA02Kw38TJx0nLCd8yr4QGLxSpW8Jiiobxc1zURIbr4VhoSET44l0uoRJ3OhNk53Ve2PDMu3tD/aDbG+WqO2/g2gI+ajfMR93oChXANkwe5d47lbo+QcqQ2BTJWNoi6WtTH8B9kRD+IA5torHV9C1oJK8ZlqeHs7oa5wNnjr9kQLeyaBT3p3IdIFpVooLpbM8ICkAoUHOvSLubJzDaZA3P4/ycBQOvavm5e0vTOwUVdPG4pVMXQYdduWUVUIYctq6cS74X9cuPd7TpoYyHWqKxDB4m3FxQgsUdJeAUnJpoS4rPAJxQoTGz6YHijXcNhNI="
